# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py314"
line-length = 120

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN401",   # Dynamically typed expressions (typing.Any) are disallowed
    "D202",     # No blank lines allowed after function docstring
    "D203",     # no-blank-line-before-class (incompatible with formatter)
    "D212",     # multi-line-summary-first-line (incompatible with formatter)
    "CPY001",   # Missing copyright notice at top of file
    "COM812",   # incompatible with formatter
    "ISC001",   # incompatible with formatter
    "TD002",    # Missing TODO author
    "TD003",    # Missing TODO issue
    "TD006",    # Invalid TODO
]

[lint.per-file-ignores]
"tests/*" = [
    "ARG001",   # Unused function arguments
    "ARG002",   # Unused method argument
    "ANN001",   # Missing type annotation
    "DTZ001",   # Datetime without tzinfo
    "E501",     # Line length
    "E711",     # None comparison
    "E712",     # True False comparison
    "INP001",   # Implicit namespace package
    "PLR2004",  # Magic values
    "PT022",    # Yield in fixture
    "S101",     # Use of assert
    "SLF001",   # Private member access
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pylint]
max-args = 8

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25
