name: Drime API Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SAT"

permissions:
  contents: write
  pull-requests: write

jobs:
  check_swagger_spec:
    name: Check swagger spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Pull Drime API spec
        run: wget -O drime_api/swagger.yaml https://app.drime.cloud/swagger.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: Update Drime API swagger file
          branch: drime-swagger-api-update
          delete-branch: true
          title: "Update Drime API file"
